### ISSUE TITLE
Gate LED remains lit when unplugging Trig

### ISSUE THREAD

**Issue by patrickdowling** [float32/Penrose#1]
So to transfer this over from MW:

> It does feel like the Gate LED is on more often than expected and if I unplug the "other" end of the Trig cable (i.e. leaving it in module but floating) it's permanently lit.
>
>Giving the code a quick peek: ProcessDAC() only gets called if there's something to do, won't that delay the call to FinishWrite()?

Having the gate attached to `LDAC` is elegant in hardware, but muddles the software abstraction. Honestly I'd have poke at solutions in code to see how they feel, as you said it can seem a bit inelegant...

Something related to maybe check is what happens if a new value arrives while the last gate is still high, which would seem to require at least a small pulse?

**Comment by float32** [comment]
This should be fixed with commit bd9a7f9b2c5b7df52bcea5d3fb5560101999558c

> Something related to maybe check is what happens if a new value arrives while the last gate is still high, which would seem to require at least a small pulse?

In `dac::BeginWrite()`, the `LDAC` signal is always deasserted immediately before writing to the DAC, and then reasserted after, so the gates will never run together. This is how the original firmware works too.

**Comment by patrickdowling** [comment]
👍
